name: compile_mac

on: [push]

env:
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  compile_Ninja:
    runs-on: macos-latest

    steps:
      - name: Checkout wxMaxima from git
        uses: actions/checkout@v3
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 15
      - name: Install the dependencies
        run: |
             export PATH=$PATH:/usr/local/opt/gettext/bin
             export HOMEBREW_NO_AUTO_UPDATE=1
             set -e
             brew install gettext ninja pandoc wxwidgets
             set +e
      - name: Configure wxMaxima
        run: |
             mkdir ../build-wxm
             cmake -S . -B ../build-wxm -G Ninja -DCMAKE_INSTALL_PREFIX=. -DCMAKE_UNITY_BUILD_BATCH_SIZE=8 -DWXM_UNIT_TESTS=YES -DCMAKE_UNITY_BUILD=YES

      - name: Check Info.plist
        run: |
             ls -l ../build-wxm/src/Info.plist
      - name: Compile wxMaxima
        run: |
             cmake --build ../build-wxm
      - name: Install wxMaxima
        run: |
             cmake --install ../build-wxm
      - name: Package wxMaxima
        run: |
             cd ../build-wxm
             cpack -G DragNDrop

  compile_Make:
    runs-on: macos-latest

    steps:
      - name: Checkout_git
        uses: actions/checkout@v3
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 15
      - name: Install the Dependencies
        run: |
             export PATH=$PATH:/usr/local/opt/gettext/bin
             export HOMEBREW_NO_AUTO_UPDATE=1
             set -e
             brew install gettext pandoc wxwidgets
             set +e
      - name: configure
        run: |
             mkdir ../build-wxm
             cmake -S . -B ../build-wxm -DCMAKE_INSTALL_PREFIX=.
      - name: plist_check
        run: |
             ls -l ../build-wxm/src/Info.plist
      - name: compile
        run: |
             cmake --build ../build-wxm
      - name: install
        run: |
             cmake --install ../build-wxm
